name: agdoc
services:
  - name: agdoc
    github:
      repo: williammw/agdoc
      branch: master
      deploy_on_push: true
    build_command: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    run_command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    envs:
      - key: PYTHONUNBUFFERED
        value: "1"
    http_port: 8080